<a href="https://colab.research.google.com/github/jaisal1311/College-Stuff/blob/master/AI/AI_pracs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Romania Map



![ROMANIA MAP](https://miro.medium.com/max/863/1*Lx_LKzRCpXnYaEn-ZdUu1Q.png)

In [63]:
romania_map = {
    'Arad': ['Sibiu', 'Timisoara', 'Zerind'],
    'Bucharest': ['Fagarus', 'Giurgiu', 'Pitesti', 'Urziceni'],
    'Craiova': ['Drobeta', 'Pitesti', 'Rimnicu Vilcea'],
    'Drobeta': ['Craiova', 'Mehadia'],
    'Eforie': ['Hirsova'],
    'Fagarus': ['Bucharest', 'Sibiu'],
    'Giurgiu': ['Bucharest'],
    'Hirsova': ['Eforie', 'Urziceni'],
    'Iasi': ['Neamt', 'Vaslui'],
    'Lugoj': ['Mehadia', 'Timisoara'],
    'Mehadia': ['Drobeta', 'Lugoj'],
    'Neamt': ['Iasi'],
    'Oradea': ['Sibiu', 'Zerind'],
    'Pitesti': ['Bucharest', 'Craiova', 'Rimnicu Vilcea'],
    'Rimnicu Vilcea': ['Craiova', 'Pitesti', 'Sibiu'],
    'Sibiu': ['Oradea', 'Arad','Fagarus', 'Rimnicu Vilcea'],
    'Timisoara':['Arad', 'Lugoj'],
    'Urziceni': ['Bucharest', 'Hirsova', 'Vaslui'],
    'Vaslui': ['Iasi', 'Urziceni'],
    'Zerind': ['Arad', 'Oradea'],
}

## BFS traversal until node is found

In [64]:
def BFS_traversal(G, s, d):
    if s == d:
        return 'Masti Nai...😅'
    visited = [s]
    q = [s]
    while q:
        u = q.pop(0)
        for v in G[u]:
            if v not in visited:
                if v == d:
                    visited.append(v)
                    return ' => '.join(visited)
                else:
                    q.append(v)
                    visited.append(v)
    return 'Not Found..😞'

BFS_traversal(romania_map, 'Arad', 'Bucharest')

'Arad => Sibiu => Timisoara => Zerind => Oradea => Fagarus => Rimnicu Vilcea => Lugoj => Bucharest'

## BFS Shortest Path

In [65]:
def BFS_shortest_path(G, source, destination):
    visited= []
    queue = [[source]]

    if source == destination:
        return 'No masti..😅'
    
    while queue:
        path = queue.pop(0)
        node = path[-1]

        if node not in visited:
            neighbours = G[node]
        
        for neighbour in neighbours:
            new_path = list(path)
            new_path.append(neighbour)
            queue.append(new_path)

            if neighbour == destination:
                return (' => '.join(new_path), '✨')
        visited.append(node)
    return 'Not Found..😞'
BFS_shortest_path(romania_map, 'Arad', 'Bucharest')

('Arad => Sibiu => Fagarus => Bucharest', '✨')

In [ ]:
def DFS(graph, start):
    visited, stack = set(), [start]
    while stack:
        vertex = stack.pop()
        if vertex not in visited:
            visited.add(vertex)
            stack.extend(graph[vertex])
    return visited

DFS(romania_map, 'Craiova')

{'Arad',
 'Bucharest',
 'Craiova',
 'Drobeta',
 'Eforie',
 'Fagarus',
 'Giurgiu',
 'Hirsova',
 'Iasi',
 'Lugoj',
 'Mehadia',
 'Neamt',
 'Oradea',
 'Pitesti',
 'Rimnicu Vilcea',
 'Sibiu',
 'Timisoara',
 'Urziceni',
 'Vaslui',
 'Zerind'}

## IRIS

In [77]:
iris = pd.read_csv('/content/iris_csv.csv')
iris.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [76]:
from sklearn.datasets import load_iris 
from sklearn.linear_model import LogisticRegression 
X, y = load_iris(return_X_y=True) 
clf = LogisticRegression(random_state=0).fit(X, y) 
clf.score(X, y) 

[5.1 3.4 1.5 0.2] 0


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9733333333333334

In [72]:
clf.predict(X)[39]

0

## Diabetes


In [55]:
import numpy as np
data = pd.read_csv('/content/diabetes.csv')
data 

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [56]:
inputs = torch.from_numpy(np.array(data.iloc[:, :-1])).float()
outputs = torch.from_numpy(np.array(data.iloc[:, -1])).float()

outputs.unique()

tensor([0., 1.])

In [57]:
model = torch.nn.Sequential(
    torch.nn.Linear(8, 16),
    torch.nn.ReLU(),
    torch.nn.Linear(16, 32),
    torch.nn.Tanh(),
    torch.nn.Linear(32, 16),
    torch.nn.LeakyReLU(),
    torch.nn.Linear(16, 8),
    torch.nn.Sigmoid(),
    torch.nn.Linear(8, 1),
    torch.nn.Sigmoid(),
)

In [58]:
loss_fn = F.binary_cross_entropy
optimizer = torch.optim.SGD(model.parameters(), lr=0.00005)

In [78]:
model.train()
for t in range(5000):

    Y_pred = model(inputs)

    loss = loss_fn(Y_pred, outputs)
    
    if t % 100 == 0:
        print("Epoch:", t, "\tLoss:", loss.item())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Using a target size (torch.Size([768])) that is different to the input size (torch.Size([768, 1])) is deprecated. Please ensure they have the same size.
  


Epoch: 0 	Loss: 0.7153638005256653
Epoch: 100 	Loss: 0.7148651480674744
Epoch: 200 	Loss: 0.71437007188797
Epoch: 300 	Loss: 0.7138788104057312
Epoch: 400 	Loss: 0.7133910059928894
Epoch: 500 	Loss: 0.7129068374633789
Epoch: 600 	Loss: 0.7124262452125549
Epoch: 700 	Loss: 0.7119492888450623
Epoch: 800 	Loss: 0.7114758491516113
Epoch: 900 	Loss: 0.7110059857368469
Epoch: 1000 	Loss: 0.7105396389961243
Epoch: 1100 	Loss: 0.7100768685340881
Epoch: 1200 	Loss: 0.7096174359321594
Epoch: 1300 	Loss: 0.7091614603996277
Epoch: 1400 	Loss: 0.7087087631225586
Epoch: 1500 	Loss: 0.7082595229148865
Epoch: 1600 	Loss: 0.707813560962677
Epoch: 1700 	Loss: 0.7073708176612854
Epoch: 1800 	Loss: 0.7069314122200012
Epoch: 1900 	Loss: 0.7064952254295349
Epoch: 2000 	Loss: 0.7060623168945312
Epoch: 2100 	Loss: 0.7056325078010559
Epoch: 2200 	Loss: 0.7052059173583984
Epoch: 2300 	Loss: 0.7047824859619141
Epoch: 2400 	Loss: 0.7043620944023132
Epoch: 2500 	Loss: 0.7039448618888855
Epoch: 2600 	Loss: 0.703530

In [60]:
print(torch.round(model(inputs[99])))
print(outputs[99])

tensor([1.], grad_fn=<RoundBackward>)
tensor(1.)


PIMA Pytorch

## Logical Units NN